Ledstrip animations
bobbycar-graz/bobbycar-boardcomputer-firmware pull request #305
Opened 2022-04-18 12:19 UTC by Greyhash-dev

Added 2 new animations - more to come?

2022-04-18 12:28 UTC, CommanderRedYT commented
Please make sonarcloud happy!

2022-04-18 13:13 UTC, Greyhash-dev commented
This commit broke the Snake Animation

2022-04-19 07:41 UTC, CommanderRedYT requested changes

2022-04-19 07:41 UTC, CommanderRedYT commented on main/ledstrip.cpp
> +        case LedstripAnimation::SpeedOMeter: showEfficiencyAnimation(); break;
Is this a speed animation or efficiency animation? That's two different things

2022-04-19 07:41 UTC, CommanderRedYT commented on main/ledstrip.cpp
> +    //          );
Why is there code that is commented out?

2022-04-19 07:41 UTC, CommanderRedYT commented on main/ledstrip.cpp
> +        {
Formatting

2022-04-19 09:29 UTC, Greyhash-dev commented on main/ledstrip.cpp
> +        case LedstripAnimation::SpeedOMeter: showEfficiencyAnimation(); break;
There are 2 new Animations: One shows snakes speedsync (showSnakeAnimation) and one shows the current wh/km as a color... Please read commit history...

2022-04-19 09:31 UTC, Greyhash-dev commented on main/ledstrip.cpp
> +    //          );
Because it is the old code of the previous solution... I did not want to remove it permanently, because it could be useful for a animation I might make in the future.

2022-04-19 19:39 UTC, CommanderRedYT commented on main/ledstrip.cpp
> +        case LedstripAnimation::SpeedOMeter: showEfficiencyAnimation(); break;
I can read, and that is why I ask why the function does not have the same name as the enum

2022-04-19 20:00 UTC, CommanderRedYT commented on main/ledstrip.cpp
> +    //          );
If you need to preserve code, please put it in a separate branch.

https://stackoverflow.com/a/3664326

2022-04-22 20:55 UTC, CommanderRedYT approved these changes
Thanks for fixing stuff

2022-04-22 21:17 UTC, merged