Speed screen improvements, Measurement Mode
bobbycar-graz/bobbycar-boardcomputer-firmware pull request #348
Opened 2022-07-17 18:22 UTC by peterpoetzi

2022-07-17 18:49 UTC, CommanderRedYT requested changes
Fix formatting

2022-07-17 18:49 UTC, CommanderRedYT commented on main/displays/measurementdisplay.h
> +#include "modes/ignoreinputmode.h"
Why do you need ignore input mode for something that measures driving statistics?

2022-07-17 18:49 UTC, CommanderRedYT commented on main/displays/measurementdisplay.cpp
> +                .time = std::chrono::floor<std::chrono::milliseconds>(espchrono::millis_clock::now() - *m_start_time),
m_start_time could be std::nullopt

2022-07-17 18:49 UTC, CommanderRedYT commented on main/displays/measurementdisplay.cpp
> +        MeasurementDisplayItem(const MeasurementDisplay::Result result) : m_result{result} {}
Remove copy

2022-07-17 18:49 UTC, CommanderRedYT commented on main/displays/speedinfodisplay.cpp
> +        tft.setTextSize(2);
You could also use &s / &m as documented in 0xFEEDC0DE64/esp-gui-lib

2022-07-17 18:49 UTC, CommanderRedYT commented on main/newsettings.h
> +
Why so many empty lines?

2022-08-15 16:36 UTC, peterpoetzi commented on main/displays/measurementdisplay.h
> +#include "modes/ignoreinputmode.h"
Will be addressed in https://github.com/bobbycar-graz/bobbycar-boardcomputer-firmware/pull/352

2022-08-15 16:36 UTC, peterpoetzi commented on main/displays/measurementdisplay.cpp
> +                .time = std::chrono::floor<std::chrono::milliseconds>(espchrono::millis_clock::now() - *m_start_time),
Will be addressed in https://github.com/bobbycar-graz/bobbycar-boardcomputer-firmware/pull/352

2022-08-15 16:36 UTC, peterpoetzi commented on main/displays/measurementdisplay.cpp
> +        MeasurementDisplayItem(const MeasurementDisplay::Result result) : m_result{result} {}
Will be addressed in https://github.com/bobbycar-graz/bobbycar-boardcomputer-firmware/pull/352

2022-08-15 16:37 UTC, peterpoetzi commented on main/displays/speedinfodisplay.cpp
> +        tft.setTextSize(2);
This does not work for setting the text size, only for changing the font. However, I do not like the large font and find the regular font with 2x the size more readable

2022-08-15 16:37 UTC, peterpoetzi commented on main/newsettings.h
> +
Will be addressed in https://github.com/bobbycar-graz/bobbycar-boardcomputer-firmware/pull/352

2022-08-16 10:26 UTC, CommanderRedYT approved these changes

2022-09-17 15:55 UTC, merged